export const SET_ACTIVE_MEDIA_TYPE = 'SET_ACTIVE_MEDIA_TYPE';
export const SET_SETPS_COUNT = 'SET_SETPS_COUNT';
export const SET_CALORIES_COUNT = 'SET_CALORIES_COUNT';
export const SET_USER_GOAL = 'SET_USER_GOAL';
