export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_SUCCEEDED = 'AUTHENTICATE_SUCCEEDED';
export const AUTHENTICATE_FAILED = 'AUTHENTICATE_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
